INFO (2022-06-29 12:58:01,227 root We are into function 
ERROR (2022-06-29 12:58:01,227 root division by zero 
Traceback (most recent call last):
  File "D:\Study\Data Science\Python\pythonProjects\pythonProjects\LoggingProject.py\Test1.py", line 6, in divide
    s= a/b
ZeroDivisionError: division by zero
CRITICAL (2022-06-29 12:58:01,227 root unable to read the file test1.log 
ERROR (2022-06-29 12:58:01,228 root division by zero 
